### ISSUE TITLE
Getting a 'fail to import'

### ISSUE THREAD

**Issue by jimsmithm3** [Theodor-Lindberg/NPP-TOML-Syntax#1]
Using on v7.7.1 32-bit version

The User Defined Language dialog V.2.1.0.12

**Comment by btkfrank** [comment]
same here `v7.8.4` `32-bit` version

**Comment by Theodor-Lindberg** [comment]
Sorry for slow updates, I will try to look into it.

**Comment by Theodor-Lindberg** [comment]
Weird, I just tested with ```v7.8.4``` ```32-bit```, ```v7.8.4``` ```64-bit``` and  ```v7.5.9``` ```64-bit``` and had no issues. I'm also using User Defined Language dialog ```V.2.1.0.12```. I will keep looking but it will be difficult since I can't reproduce it myself.

**Comment by btkfrank** [comment]
> Weird, I just tested with `v7.8.4` `32-bit`, `v7.8.4` `64-bit` and `v7.5.9` `64-bit` and had no issues. I'm also using User Defined Language dialog `V.2.1.0.12`. I will keep looking but it will be difficult since I can't reproduce it myself.

here is my screenshot
![image](https://user-images.githubusercontent.com/5600309/74801021-522c4000-52a3-11ea-930d-837529a886f6.png)

BTW I am on windows 10

**Comment by Theodor-Lindberg** [comment]
I'm also on Windows 10, how are you downloading the ```TOML.xml``` file?

**Comment by btkfrank** [comment]
> I'm also on Windows 10, how are you downloading the `TOML.xml` file?

sorry my bad, I didn't download it properly.

This issue can be closed

Thank you @Theodor-Lindberg

**Comment by Theodor-Lindberg** [comment]
No problem, I will try to improve the instructions.

**Comment by ElvenChaos** [comment]
I'm having this issue with v7.8.6 32-bit, and I've tried both download methods. I feel like I got a correct .xml file both times, so I don't know what's going on.

EDIT: Managed to get it to work by putting the file in the user defined languages folder manually.

As a side note, the style backgrounds should be set to "none" instead of "white" for compatibility with dark themes. To do this, simply go to the stylers and right-click the background color to give it some diagonal lines, which indicate a transparent background.

Here is an upload of the file with the change if you want to reference it.
[TOML.zip](https://github.com/Theodor-Lindberg/NPP-TOML-Syntax/files/4567466/TOML.zip)

**Comment by Theodor-Lindberg** [comment]
> I'm having this issue with v7.8.6 32-bit, and I've tried both download methods. I feel like I got a correct .xml file both times, so I don't know what's going on.
> 
> EDIT: Managed to get it to work by putting the file in the user defined languages folder manually.
> 
> As a side note, the style backgrounds should be set to "none" instead of "white" for compatibility with dark themes. To do this, simply go to the stylers and right-click the background color to give it some diagonal lines, which indicate a transparent background.
> 
> Here is an upload of the file with the change if you want to reference it.
> [TOML.zip](https://github.com/Theodor-Lindberg/NPP-TOML-Syntax/files/4567466/TOML.zip)

Hi, I'm glad it worked out and thank you for your contribution. I'll update the documentation with that information and look into the compatibility with dark themes as soon as I find time.
